name: Wake Up Supabase

on:
  schedule:
    # Jalan setiap hari jam 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  ping_database:
    runs-on: ubuntu-latest
    steps:
      - name: Force Database Write (Update)
        run: |
          # Ambil jam sekarang buat bukti update
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          
          # Lakukan PATCH (Update) ke baris id=1
          # Kita ubah kolom 'message' dengan waktu terbaru
          curl -f -X PATCH "${{ secrets.SUPABASE_URL }}/rest/v1/keep_alive?id=eq.1" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}" \
          -H "Content-Type: application/json" \
          -H "Prefer: return=representation" \
          -d "{\"message\": \"Keep Awake! $TIMESTAMP\"}"
